### ISSUE TITLE
Invalid conditional syntax in Underlords gameinfo.gi

### ISSUE THREAD

**Issue by xPaw** [SteamDatabase/ValveKeyValue#24]
File: https://github.com/SteamDatabase/GameTracking-Underlords/blob/master/game/dac/gameinfo.gi

```
System.IO.InvalidDataException: Invalid conditional syntax "!$MOBILE && !$MOBILE_RSRC && !$BUILDALLSHADERS_RUN && !$CONTENTBUILDER_RUN && !$VMPI_GAMEINFO"
 ---> System.InvalidOperationException: Bad condition syntax.
   at ValveKeyValue.KVConditionEvaluator.ReadToken(TextReader reader)
   at ValveKeyValue.KVConditionEvaluator.Evalute(String expressionText)
   --- End of inner exception stack trace ---
   at ValveKeyValue.KVConditionEvaluator.Evalute(String expressionText)
   at ValveKeyValue.Deserialization.KV1TextReader.HandleCondition(String text)
   at ValveKeyValue.Deserialization.KV1TextReader.ReadObject()
   at ValveKeyValue.KVSerializer.Deserialize(Stream stream, KVSerializerOptions options)
   at GUI.Utils.AdvancedGuiFileLoader.FindAndLoadSearchPaths() in D:\GitHub\ValveResourceFormat\GUI\Utils\AdvancedGuiFileLoader.cs:line 160
```

**Comment by xPaw** [comment]
Its failing because `IsReadableVariableCharacter` returns false for `_` in `MOBILE_RSRC`.
